# Numpy
numeric python
Arrays, arrays multidimensionais (matriz)
Elementos tem que ter o mesmo
Processamento rápido

In [1]:
# importar a biblioteca
import numpy as np

In [2]:
# Criar um array
array = np.array([1, 3, 5, 7])
print(array)

[1 3 5 7]


In [3]:
#Tipo: type()
print(type(array))

<class 'numpy.ndarray'>


In [4]:
# Definir o tipo dos elementos
# Array de floats
array_float = np.array([1.2, 3.6, 4.99999])
print(array_float)

[1.2     3.6     4.99999]


In [6]:
array_float = np.array([1, 2, 30], dtype = np.float64)
print(array_float)

[ 1.  2. 30.]


In [7]:
# Array de inteiros
array_int = np.array([1, 2, 30], dtype = np.int32)
print(array_int)

[ 1  2 30]


## Alterar o tipo do array

In [9]:
# Alterar de float para inteiro
array1 = np.array([1.2, 4.8, 8.3, 9.999])

array1_convertido = array1.astype(np.int32)
print(array1_convertido)

[1 4 8 9]


In [11]:
# Alterar de inteiro para float
array2 = np.array([1, 6, 8, 3])

array2_int = array2.astype(np.float64)
print(array2_int)

[1. 6. 8. 3.]
